### ISSUE TITLE
Recurring transactions & automatic budgets do not get triggered

### ISSUE THREAD

**Issue by marecabo** [hassio-addons/addon-firefly-iii#11]
# Problem/Motivation

Certain features of Firefly III (like recurring transactions and automatic budgets) require a daily cron job.

See https://docs.firefly-iii.org/advanced-installation/cron

## Expected behavior

It would be great, if this add-on would contain a mechanism to trigger the creation of recurring transactions / rollover of automatic budgets by itself.

## Actual behavior

Recurring transactions do not get created on their designated dates. Automatic budgets do not roll over.

## Steps to reproduce

Create a recurring transaction and observe it not getting created on its designated day.

## External Workaround

1. Create a personal access token at http://your-ha-ip:3473/profile and put it into your secrets.yaml
2. Setup the following automation, adapt it whether you use SSL or not

    #### configuration.yaml
    ```yaml
    shell_command:
      firefly_cron: "/usr/bin/curl -X GET http://localhost:3473/cron/run/{{access_token}}"
    #  firefly_cron_ssl: "/usr/bin/curl -X GET https://localhost:3473/cron/run/{{access_token}} --insecure"
    ```

    #### automations.yaml
    ```yaml
    - alias: 'Firefly III Cron Job'
      description: 'Creates recurrent transactions in Firefly III'
      trigger:
        - platform: time
          at: "00:00:01"
      action:
        - service: shell_command.firefly_cron
          data:
            access_token: !secret firefly_access_token
    #     - service: shell_command.firefly_cron_ssl
    #       data:
    #         access_token: !secret firefly_access_token
    ```

## Proposed changes

Would it fit into the add-on architecture to add cron to the add-on with a crontab as proposed in the Firefly III documentation?

```cron
# cron job for Firefly III (daily at 00:01)
1 0 * * * /usr/bin/php /var/www/firefly-iii/artisan firefly-iii:cron
```
